### ISSUE TITLE
thanks for this good plugin but i can't create new risk.

### ISSUE THREAD

**Issue by bsban** [rolesoftware/redrisk#2]
I meet the message 'title cannot be blank' when I create a new risk.

How and What I do?

**Comment by rodrigogirao** [comment]
Hi.

To create a risk you must enter a title.
The title is required because it is the way to identify a risk.

Thanks for use the plugin.

Regards.

**Comment by bsban** [comment]
yes, it is identifier I know. 
I wrote title and other items and click "create risk" button then the title was disappear and put "title cannot be blank".

thank you

나의 iPhone에서 보냄
1. 3. 17. 오전 9:35 Rodrigo Girão notifications@github.com 작성:

**Comment by DDallongeville** [comment]
Hi,
I had this problem and I found the solution.
For this, you must make the attributes available in the model "risk"
add to "app/models/risk.rb"
"attr_accessible :title, :status, :origin, :effort, :cost, :description, :source, :category, :probability, :impact, :priority, :identification_date, :created_by, :assigned_to, :strategy, :trigger"
And add to "app/models/action_plan.rb"
"attr_accessible :effective, :title, :kind, :description, :assigned_to, :term, :finish_date"

**Comment by sksemenov** [comment]
I have the same issue on redmine 3 ...
May we have the fix above merged into master ?

**Comment by DDallongeville** [comment]
You can clone the plugin on my github page, it runs on redmine 3
https://github.com/DDallongeville/redrisk

**Comment by rodrigogirao** [comment]
Fixed on commits 40d0fc3 and 4029390
Thank you @DDallongeville, your modifications were incorporated on version 1.0.1. Feel free to make pull requests.

Regards,
