### ISSUE TITLE
Campo "Atribuído Para"

### ISSUE THREAD

**Issue by liomoura** [rolesoftware/redrisk#3]
Ao atribuir ação de um risco para algum integrante do projeto, o campo "Atribuído Para" apresenta o ID  do usuário ao invés do label nome, conforme imagem abaixo, está correto ?

![image](https://cloud.githubusercontent.com/assets/10420467/6943181/ab2a20de-d862-11e4-8020-3529e7723c73.png)

Atenciosamente,

**Comment by rodrigogirao** [comment]
Consertado no commit 221d123b6600aa9caecde5a93f568ec77cef6c29.
Por favor atualize para a versão 1.0.1 para testar as modificações.

Atenciosamente.
