### ISSUE TITLE
Can not edit risks & actions

### ISSUE THREAD

**Issue by sksemenov** [rolesoftware/redrisk#4]
Setup: Redmine: 3.1 (master), Ruby 2.2, Rails 4.2

On issue or action update the following error message is displayed:

Page not found
The page you were trying to access doesn't exist or has been removed.

**Comment by DDallongeville** [comment]
Edit the file "redrisk/config/routes.rb" and change put to patch

**Comment by rodrigogirao** [comment]
In commit 01caac9cfb7ae80c41035754f37307cf047924a7 we fixed this issue to work on Rails 3.2 or higher.

Please update to version 1.0.1.

Regards,
